name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
      env:
          test_scheme: ${{ secrets.test_scheme }}
    - name: Print env
      run:
          echo $test_scheme,
    - name: install bundle
      run: Bundle install
    - name: Run testing lane
      run: Bundle exec fastlane test
