name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: install bundle
      run: Bundle install
    - name: Run testing lane
      env:
        test_scheme: ${{ secrets.test_scheme }}
      run: Bundle exec fastlane test
